name: Issue Bot

on:
  issues:
    types: [opened]

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Initialize Node.js project
        run: npm init -y

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Verify script exists
        run: ls -la .github/scripts/

      - name: Run Issue Bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/issue-bot.js || echo "Script failed, check logs"
